global:
  scrape_interval: 15s #Scrape interval to every 15 seconds.
  evaluation_interval: 15s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "cadvisor"
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets: ["172.19.0.2:8080"]